// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okblrstqjhmoaenpfcly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rYmxyc3Rxamhtb2FlbnBmY2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjA1NDEsImV4cCI6MjA2NjEzNjU0MX0.zcXJesS_qyussaYboFaAYn8x3ABxKF15EuiXr45NzCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);